// swift-tools-version: 6.0
//
// coflux-screen: the controlled side of the remote screen tab (plan 20260929-remote-desktop).
// Built by `node scripts/build-screen-helper.mjs` and shipped inside Coflux.app next to the other
// runtime binaries; never part of the worker's hot-upgrade artifact set (macOS only).

import PackageDescription

let package = Package(
    name: "coflux-screen",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .executable(name: "coflux-screen", targets: ["coflux-screen"]),
    ],
    dependencies: [
        // The generated protobuf types of the wire contract (proto/coflux/v1), regenerated by
        // `buf generate`; the helper speaks ScreenHelperFrame / DeviceEnvelope from there.
        .package(name: "CofluxSwiftClient", path: "../../packages/swift-client"),
    ],
    targets: [
        // Private CoreGraphics interfaces (CGVirtualDisplay*) declared from a local header; the
        // SDK does not ship them.
        .target(
            name: "CVirtualDisplay",
            path: "Sources/CVirtualDisplay",
            linkerSettings: [
                .linkedFramework("CoreGraphics"),
            ]
        ),
        .target(
            name: "CofluxScreenCore",
            dependencies: [
                "CVirtualDisplay",
                .product(name: "CofluxProtocol", package: "CofluxSwiftClient"),
            ],
            path: "Sources/CofluxScreenCore",
            linkerSettings: [
                .linkedFramework("AppKit"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("IOKit"),
                .linkedFramework("ScreenCaptureKit"),
                .linkedFramework("VideoToolbox"),
            ]
        ),
        .executableTarget(
            name: "coflux-screen",
            dependencies: ["CofluxScreenCore"],
            path: "Sources/coflux-screen"
        ),
        .testTarget(
            name: "CofluxScreenCoreTests",
            dependencies: ["CofluxScreenCore"],
            path: "Tests/CofluxScreenCoreTests"
        ),
    ],
    swiftLanguageModes: [.v5]
)
