import assert from "node:assert/strict";
import { test } from "node:test";

import {
  isUsableAgentSessionId,
  loadTranscript,
  parseTranscript,
  parseTranscriptOutput,
  transcriptCommand,
  TRANSCRIPT_TAIL_BYTES,
  type TranscriptExec,
} from "./terminal-transcript";

/** Fixture ids only — the real ones are generated by the agent, not by us. */
const CLAUDE_ID = "6fd5b5f9-959b-4845-91b8-e2f6cefc1a51";
const CODEX_ID = "01a09538-e6de-7ca3-88e7-dd35d65e84f1";

function jsonl(...records: unknown[]): string {
  return `${records.map((record) => JSON.stringify(record)).join("\n")}\n`;
}

/* ------------------------------------------------------------------ *
 * Claude Code
 * ------------------------------------------------------------------ */

/**
 * Every record here except the two prompts and the one assistant text is a trap observed in a
 * real file: in one sampled tail 85 of 93 `user` records were `tool_result` payloads, 5 carried
 * `isMeta`, and 2 were slash-command bookkeeping.
 */
const CLAUDE_FIXTURE = jsonl(
  { type: "last-prompt", value: "还有略有点卡" },
  { type: "ai-title", title: "x" },
  { type: "file-history-snapshot", files: [] },
  { type: "atis-latch" },
  { type: "system", content: "hook ran" },
  { type: "user", isSidechain: false, message: { role: "user", content: "还有略有点卡, 或者说松手后先隐藏缩略图再操作数据库呢?" } },
  {
    type: "assistant",
    isSidechain: false,
    message: { role: "assistant", content: [{ type: "thinking", thinking: "内部推演，不该进纸面", signature: "…" }] },
  },
  {
    type: "assistant",
    isSidechain: false,
    message: {
      role: "assistant",
      content: [{ type: "text", text: "验过了，两件都成立。\n\n段落之间的换行是作者写的，不是终端折的。" }],
    },
  },
  {
    type: "assistant",
    isSidechain: false,
    message: {
      role: "assistant",
      content: [{ type: "tool_use", id: "toolu_1", name: "Bash", input: { command: "git status", description: "看看改了啥" } }],
    },
  },
  {
    type: "user",
    isSidechain: false,
    message: { role: "user", content: [{ tool_use_id: "toolu_1", type: "tool_result", content: "824:private struct …" }] },
  },
  { type: "user", isMeta: true, message: { role: "user", content: "Caveat: the messages below were generated by …" } },
  { type: "user", isSidechain: false, message: { role: "user", content: "<command-name>/clear</command-name>" } },
  {
    type: "user",
    isSidechain: false,
    message: { role: "user", content: [{ type: "text", text: "[Request interrupted by user]" }] },
  },
  {
    type: "user",
    isSidechain: true,
    message: { role: "user", content: "子 agent 的提问，不该出现在这一页" },
  },
  {
    type: "assistant",
    isSidechain: true,
    message: { role: "assistant", content: [{ type: "text", text: "子 agent 的回答，同样不该出现" }] },
  },
  {
    type: "user",
    isSidechain: false,
    message: { role: "user", content: [{ type: "text", text: "继续吧" }] },
  },
);

test("claude：只留人类提问与 agent 正文，工具调用压成一行地标", () => {
  assert.deepEqual(parseTranscript("claude", CLAUDE_FIXTURE), [
    { kind: "prompt", text: "还有略有点卡, 或者说松手后先隐藏缩略图再操作数据库呢?" },
    { kind: "prose", text: "验过了，两件都成立。\n\n段落之间的换行是作者写的，不是终端折的。" },
    { kind: "tool", label: "Bash(git status)" },
    { kind: "prompt", text: "继续吧" },
  ]);
});

test("claude：tool_result / isMeta / 斜杠命令 / sidechain / 中断标记一条都不进纸面", () => {
  const entries = parseTranscript("claude", CLAUDE_FIXTURE);
  const texts = entries.map((entry) => (entry.kind === "tool" ? entry.label : entry.text)).join("\n");
  for (const forbidden of [
    "824:private struct",
    "Caveat:",
    "<command-name>",
    "[Request interrupted by user]",
    "子 agent",
    "内部推演",
  ]) {
    assert.equal(texts.includes(forbidden), false, `不该出现：${forbidden}`);
  }
});

test("claude：允许名单之外的记录类型一律忽略，不靠猜", () => {
  const unknown = jsonl(
    { type: "cost-state", usd: 1 },
    { type: "continued-in", sessionId: CLAUDE_ID },
    { type: "queue-operation", op: "enqueue" },
    { type: "permission-mode", mode: "bypassPermissions" },
    { type: "attachment", path: "/tmp/x.png" },
  );
  assert.deepEqual(parseTranscript("claude", unknown), []);
});

/* ------------------------------------------------------------------ *
 * Codex
 * ------------------------------------------------------------------ */

/** The TUI shape (`codex-tui` / `codex_cli_rs`), which is the one that must be covered. */
const CODEX_FIXTURE = jsonl(
  { timestamp: "t", type: "session_meta", payload: { id: CODEX_ID, originator: "codex-tui" } },
  { type: "event_msg", payload: { type: "task_started", turn_id: "turn-1" } },
  { type: "event_msg", payload: { type: "token_count", info: {} } },
  { type: "token_usage_record", payload: { thread_id: CODEX_ID } },
  { type: "world_state", payload: { full: true, state: {} } },
  { type: "turn_context", payload: { turn_id: "turn-1", cwd: "/x" } },
  { type: "compacted", payload: { message: "上一轮模型的总结，不是对话" } },
  {
    type: "response_item",
    payload: { type: "message", role: "developer", content: [{ type: "input_text", text: "## Memory\n开发者指令" }] },
  },
  {
    type: "response_item",
    payload: {
      type: "message",
      role: "user",
      content: [
        { type: "input_text", text: "<recommended_plugins>\nHere is a list of plugins…\n</recommended_plugins>" },
        { type: "input_text", text: "# AGENTS.md instructions for /Users/wsq/Workspace/coflux\n\n<INSTRUCTIONS>\n…" },
        { type: "input_text", text: "<environment_context>\n  <cwd>/Users/wsq/Workspace/coflux</cwd>\n</environment_context>" },
        { type: "input_text", text: "<skill>\n<name>dev:explore</name>\n</skill>" },
      ],
    },
  },
  {
    type: "response_item",
    payload: {
      type: "message",
      role: "user",
      content: [{ type: "input_text", text: "我有个想法, 我们能直接把这个集成进来吗" }],
    },
  },
  { type: "response_item", payload: { type: "reasoning", summary: [], encrypted_content: "gAAAA…" } },
  {
    type: "response_item",
    payload: {
      type: "custom_tool_call",
      name: "exec",
      input: 'text(await tools.exec_command({cmd:"git status --short"}));\n',
    },
  },
  { type: "response_item", payload: { type: "custom_tool_call_output", output: [{ type: "input_text", text: "…" }] } },
  {
    type: "response_item",
    payload: { type: "function_call", name: "js", arguments: '{"code":"var app = await cua.getApp();","title":"检查界面"}' },
  },
  {
    type: "response_item",
    payload: {
      type: "message",
      role: "assistant",
      phase: "final_answer",
      content: [{ type: "output_text", text: "可以集成，而且方向值得推进。\n\n这段文字换行由作者决定。" }],
    },
  },
  {
    type: "response_item",
    payload: { type: "agent_message", author: "/root", content: [{ type: "input_text", text: "Message Type: NEW_TASK" }] },
  },
);

test("codex：注入块被按形状挡掉，只留真人提问与助手正文", () => {
  assert.deepEqual(parseTranscript("codex", CODEX_FIXTURE), [
    { kind: "prompt", text: "我有个想法, 我们能直接把这个集成进来吗" },
    { kind: "tool", label: "exec(text(await tools.exec_command({cmd:\"git status --short\"}));)" },
    { kind: "tool", label: "js(var app = await cua.getApp();)" },
    { kind: "prose", text: "可以集成，而且方向值得推进。\n\n这段文字换行由作者决定。" },
  ]);
});

test("codex：developer / reasoning / agent_message / event_msg 都不是对话", () => {
  const texts = parseTranscript("codex", CODEX_FIXTURE)
    .map((entry) => (entry.kind === "tool" ? entry.label : entry.text))
    .join("\n");
  for (const forbidden of ["## Memory", "gAAAA", "NEW_TASK", "上一轮模型的总结", "<recommended_plugins>", "AGENTS.md"]) {
    assert.equal(texts.includes(forbidden), false, `不该出现：${forbidden}`);
  }
});

/* ------------------------------------------------------------------ *
 * The tail window, the header, and the states around it
 * ------------------------------------------------------------------ */

test("尾部窗口：头部标记给出截断事实，开头那半行 JSON 自然被跳过", () => {
  const partial = '{"type":"assistant","message":{"role":"assistant","content":[{"type":"te';
  const stdout = `coflux-transcript 978123 ${TRANSCRIPT_TAIL_BYTES}\n${partial}\n${CLAUDE_FIXTURE}`;
  const result = parseTranscriptOutput("claude", stdout);
  assert.equal(result.status, "ok");
  if (result.status !== "ok") return;
  assert.equal(result.document.truncated, true);
  assert.equal(result.document.entries.length, 4);
});

test("文件没超过窗口就不是截断", () => {
  const result = parseTranscriptOutput("claude", `coflux-transcript 512 ${TRANSCRIPT_TAIL_BYTES}\n${CLAUDE_FIXTURE}`);
  assert.equal(result.status, "ok");
  if (result.status !== "ok") return;
  assert.equal(result.document.truncated, false);
});

test("wc -c 的前导空格不会把头部解析弄崩", () => {
  const result = parseTranscriptOutput("claude", `coflux-transcript      978123 ${TRANSCRIPT_TAIL_BYTES}\n${CLAUDE_FIXTURE}`);
  assert.equal(result.status, "ok");
  if (result.status !== "ok") return;
  assert.equal(result.document.truncated, true);
});

test("没有头部标记就是读失败，而不是一页空白", () => {
  assert.equal(parseTranscriptOutput("claude", "==> /Users/x/a.jsonl <==\n{}\n").status, "failed");
  assert.equal(parseTranscriptOutput("claude", "").status, "failed");
});

/* ------------------------------------------------------------------ *
 * The command shape and the id
 * ------------------------------------------------------------------ */

test("会话标识永远作为独立 argv 传递，绝不拼进脚本文本", () => {
  const { command, args } = transcriptCommand("claude", CLAUDE_ID);
  assert.equal(command, "sh");
  assert.equal(args[0], "-c");
  assert.equal(args.includes(CLAUDE_ID), true);
  assert.equal(args[2], "sh"); // $0 占位，于是 $1 才是 id
  assert.equal(args[3], CLAUDE_ID);
  assert.equal(args[1]!.includes(CLAUDE_ID), false);
  assert.equal(args[1]!.includes('"$1"'), true);

  // 同一段脚本文本，换 id 只换 argv。
  const other = transcriptCommand("claude", "aaaabbbb");
  assert.equal(other.args[1], args[1]);
  assert.equal(other.args[3], "aaaabbbb");

  // codex 的脚本按日期分区找三层，同样不拼 id。
  const codex = transcriptCommand("codex", CODEX_ID);
  assert.equal(codex.args[1]!.includes(CODEX_ID), false);
  assert.equal(codex.args[1]!.includes("/sessions/*/*/*/"), true);
  assert.equal(codex.args[3], CODEX_ID);
});

test("会话标识的形状校验：能当路径片段或命令片段的一律不收", () => {
  assert.equal(isUsableAgentSessionId(CLAUDE_ID), true);
  assert.equal(isUsableAgentSessionId("01a09538_e6de.7ca3"), true);
  for (const bad of ["", "   ", "a/b", "../../etc/passwd", ".hidden", "$(whoami)", "a b", "a'b", "a*b", "x".repeat(129), undefined, null]) {
    assert.equal(isUsableAgentSessionId(bad), false, `不该接受：${String(bad)}`);
  }
});

/* ------------------------------------------------------------------ *
 * loadTranscript's states
 * ------------------------------------------------------------------ */

function execStub(result: Partial<Awaited<ReturnType<TranscriptExec>>>): { exec: TranscriptExec; calls: unknown[][] } {
  const calls: unknown[][] = [];
  const exec: TranscriptExec = async (workspaceId, command, args) => {
    calls.push([workspaceId, command, args]);
    return { ok: true, exitCode: 0, stdout: "", stderr: "", error: "", ...result };
  };
  return { exec, calls };
}

test("找不到文件与读失败是两个可分辨的状态", async () => {
  const notFound = await loadTranscript(execStub({ exitCode: 3 }).exec, {
    agent: "claude",
    agentSessionId: CLAUDE_ID,
    workspaceId: "ws-1",
  });
  assert.equal(notFound.status, "not-found");

  const failed = await loadTranscript(execStub({ exitCode: 4, stderr: "HOME is not set" }).exec, {
    agent: "claude",
    agentSessionId: CLAUDE_ID,
    workspaceId: "ws-1",
  });
  assert.equal(failed.status, "failed");
  if (failed.status !== "failed") return;
  assert.equal(failed.detail.includes("HOME is not set"), true);

  const errored = await loadTranscript(
    async () => {
      throw new Error("设备不在线");
    },
    { agent: "claude", agentSessionId: CLAUDE_ID, workspaceId: "ws-1" },
  );
  assert.equal(errored.status, "failed");
});

test("取一次快照就是一次 execInWorkspace，不看 daemonId、不分本地远程", async () => {
  const stub = execStub({ stdout: `coflux-transcript 10 ${TRANSCRIPT_TAIL_BYTES}\n${CLAUDE_FIXTURE}` });
  const result = await loadTranscript(stub.exec, { agent: "claude", agentSessionId: CLAUDE_ID, workspaceId: "ws-1" });
  assert.equal(result.status, "ok");
  assert.equal(stub.calls.length, 1);
  assert.deepEqual(stub.calls[0]![0], "ws-1");
  assert.deepEqual(stub.calls[0]![1], "sh");
});

test("agent 不在名单里、或 id 形状不对时根本不发请求", async () => {
  const stub = execStub({});
  const unknownAgent = await loadTranscript(stub.exec, { agent: "aider", agentSessionId: CLAUDE_ID, workspaceId: "ws-1" });
  assert.equal(unknownAgent.status, "failed");
  const badId = await loadTranscript(stub.exec, { agent: "claude", agentSessionId: "../x", workspaceId: "ws-1" });
  assert.equal(badId.status, "failed");
  assert.equal(stub.calls.length, 0);
});

test("解析出零条 = 一页可说明的空，而不是失败", () => {
  const result = parseTranscriptOutput("claude", `coflux-transcript 10 ${TRANSCRIPT_TAIL_BYTES}\n`);
  assert.equal(result.status, "ok");
  if (result.status !== "ok") return;
  assert.deepEqual(result.document.entries, []);
});
